---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: config
              key: db-user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config
              key: db-name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: db-pass-secret
        volumeMounts:
        - name: db-data
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
