---
apiVersion: v1
kind: Service
metadata:
  name: gitea-db
  labels:
    app: gitea
spec:
  ports:
    - port: 5432
  selector:
    app: gitea
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1
        ports:
        - containerPort: 2222
        - containerPort: 3000
        env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: gitea-db:5432
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: gitea-config
              key: db-name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: gitea-config
              key: db-user
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: db-pass-secret
        - name: SSH_DOMAIN
          value: git.kurz.site
        - name: ROOT_URL
          value: https://git.kurz.site
        - name: HTTP_PORT
          value: "3000"
        - name: SSH_PORT
          value: "2222"
        - name: DISABLE_REGISTRATION
          value: "true"
        volumeMounts:
        - name: gitea
          mountPath: "/data"
      - name: db
        image: postgres:9.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: gitea-config
              key: db-user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: gitea-config
              key: db-name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: db-pass-secret
        volumeMounts:
        - name: gitea-db
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: gitea
        persistentVolumeClaim:
          claimName: gitea
      - name: gitea-db
        persistentVolumeClaim:
          claimName: gitea-db
      - name: gitea-config
        configMap:
          name: gitea-config
