---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`git.kurz.site`)
    kind: Rule
    services:
    - name: gitea
      port: 3000
  tls:
    certResolver: letsencrypt
