namespace: gitea

bases:
- postgres
- gitea

resources:
- ingress-route.yaml

configMapGenerator:
- name: config
  literals:
  - db-name=gitea
  - db-user=gitea

secretGenerator:
- name: secret
  files:
  - db-pass-secret

