apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  template:
    spec:
      initContainers:
      - name: init-command
        image: busybox
        command:
        - "echo $(POSTGRES_SERVICE)"
