---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs-retain