- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: kubeadm init | tee /var/log/kubadm-init.log

- name: Set feature-gate for resizing volumes
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    insertafter: '^    - --tls-private-key'
    line: "    - --feature-gates=ExpandCSIVolumes=true"

- name: Wait for kube-apiserver to come online again
  wait_for:
    host: 127.0.0.1
    port: 6443
    timeout: 10

- name: Installing a Pod network add-on Weave Net (CNI)
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Copy config file for kubeadm
  block:
  - name: Create dir
    file:
      path: ~/.kube
      state: directory
  - name: Copy config file
    copy:
      src: /etc/kubernetes/admin.conf
      remote_src: yes
      dest: ~/.kube/config

- name: Fetch admin.conf
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "./artefacts/admin-{{ansible_date_time.iso8601}}"
    flat: yes
  
