
- name: Init Kubernetes cluster
  shell: "kubeadm init | tee /var/log/kubadm-init.log"

- name: Set feature-gate for resizing volumes
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    insertafter: '^    - kube-apiserver'
    line: "    - --feature-gates=ExpandCSIVolumes=true"

- name: Enable Plugin NodeRestriction
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    insertafter: '^    - kube-apiserver'
    line: "    - --enable-admission-plugins=NodeRestriction"

- name: Copy config file for kubeadm
  block:
  - name: Create dir
    file:
      path: ~/.kube
      state: directory
  - name: Copy config file
    copy:
      src: /etc/kubernetes/admin.conf
      remote_src: yes
      dest: ~/.kube/config

- name: Wait for kube-apiserver to come online again
  wait_for:
    port: 6443
    delay: 1
    timeout: 10

- name: Installing a Pod network add-on Weave Net (CNI)
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Fetch admin.conf
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "./artefacts/admin-{{ ansible_date_time.iso8601 }}"
    flat: yes
  
