---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`nextcloud.kurz.site`) || Host(`nextcloud2.kurz.site`)
    kind: Rule
    services:
    - name: nextcloud
      port: 80
  tls:
    certResolver: letsencrypt