---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`keycloak.kurz.site`)
    kind: Rule
    services:
    - name: keycloak
      port: 8080
  tls:
    certResolver: letsencrypt