
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  restartPolicy: Always
  containers:
  - name: ubuntu
    image: ubuntu
    securityContext:
      privileged: true
    command:
      - sleep
      - "259200"
    volumeMounts:
    - name: music
      mountPath: "/new/music"
  volumes:
  - name: music
    persistentVolumeClaim:
      claimName: music
# ssh kkurz@192.168.178.28:/sharedfolders/music
# /sharedfolders/music