
---
apiVersion: v1
kind: Pod
metadata:
  name: media-manager
  labels:
    app: media-manager
spec:
  restartPolicy: Always
  containers:
  - name: media-manager
    image: ubuntu
    securityContext:
      privileged: true
    command:
      - sleep
      - "604800"
    volumeMounts:
    - name: music
      mountPath: "/new/music"
    - name: movies
      mountPath: "/new/movies"
    - name: tv
      mountPath: "/new/tv"
    - name: anime
      mountPath: "/new/anime"
  volumes:
  - name: music
    persistentVolumeClaim:
      claimName: music
  - name: movies
    persistentVolumeClaim:
      claimName: movies
  - name: tv
    persistentVolumeClaim:
      claimName: tv
  - name: anime
    persistentVolumeClaim:
      claimName: anime
# apt update && DEBIAN_FRONTEND=noninteractive apt install rsync ssh vim -y
# ssh kkurz@192.168.178.28:/sharedfolders/music
# /sharedfolders/music
# rsync -auPv kkurz@192.168.178.28:/sharedfolders/movies/ /new/movies
# rsync -auPv kkurz@192.168.178.28:/sharedfolders/tv/ /new/tv
# rsync -auPv kkurz@192.168.178.28:/sharedfolders/anime/ /new/anime
# rsync -aPv -og --chown=1000:1000 --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r kkurz@192.168.178.28:/sharedfolders/movies/ /new/movies
# rsync -aPv -og --chown=1000:1000 --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r kkurz@192.168.178.28:/sharedfolders/tv/ /new/tv
# ssh -Q cipher localhost | paste -d , -s 
# cat list | parallel -j 3 rsync -aPv -og --chown=1000:1000 --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r kkurz@192.168.178.28:/sharedfolders/movies/{} /new/movies/{}
 
# ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N "
# ssh-copy-id -i ~/.ssh/id_rsa.pub kkurz@192.168.178.28
