
- name: Update all packages to the latest version
  apt:
    upgrade: dist
    cache_valid_time: 3600

- name: Install required system packages
  apt: 
    name:
    - python3-pip
    - virtualenv
    - python3-setuptools
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest 
    cache_valid_time: 3600

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: 
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest 
    update_cache: yes

- name: Install Modules for Python
  pip:
    name:
      - docker
      - docker-compose

- name: Configure Docker
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Restart Docker
  service:
    name: docker
    state: restarted