all:
  hosts:
    kubemaster0.local.kurz.site:
    kubeworker0.local.kurz.site:
  vars:
    ansible_user: ubuntu
    kubernetes_version: 1.18.2-00
  children:
    kube_master:
      hosts:
        kubemaster0.local.kurz.site:
    kube_worker:
      hosts:
        kubeworker0.local.kurz.site:
