---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
        {
            "clusterID": "9234f042-7c20-11ea-b005-002590f3680a",
            "monitors": [
                "192.168.178.54:6789"
            ]
        }
    ]
metadata:
  name: ceph-csi-config
---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    {
      "vault-test": {
        "encryptionKMSType": "vault",
        "vaultAddress": "http://vault.default.svc.cluster.local:8200",
        "vaultAuthPath": "/v1/auth/kubernetes/login",
        "vaultRole": "csi-kubernetes",
        "vaultPassphraseRoot": "/v1/secret",
        "vaultPassphrasePath": "ceph-csi/",
        "vaultCAVerify": "false"
      }
    }
metadata:
  name: ceph-csi-encryption-kms-config